package com.steffbeard.totalwar.nations.confirmations;

public enum ConfirmationType {
	TOWN_DELETE,
	NATION_DELETE,
	ALLIANCE_DELETE,
	REBEL,
	UNCLAIM_ALL,
	PURGE,
	NATION_MERGE,
	NULL,
	GROUP_CLAIM_ACTION,
	GROUP_UNCLAIM_ACTION,
	GROUP_SET_PERM_ACTION,
	GROUP_TOGGLE_ACTION
}
